name: AM32-Firmware

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install arm sdk
        run: make arm_sdk_install

      - name: build all targets
        run: make all

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware-artifact
          path: obj
